Add yaml var
build-security/integrations pull request #12
Opened 2022-02-17 10:58 UTC by CohenIdo

- add data yaml as var
- fix `elastic package check` errors

2022-02-21 10:01 UTC, eyalkraft commented on packages/cis_kubernetes_benchmark/manifest.yml
> +    show_user: true
please hide from user

2022-02-28 12:52 UTC, kfirpeled commented
please bump version number

2022-02-28 12:59 UTC, kfirpeled commented
another issue is when adding integration for the first time the data is missing the proper formatting:
<img width="785" alt="Screen Shot 2022-02-28 at 14 58 07" src="https://user-images.githubusercontent.com/61654899/155987468-6b136b14-a1a6-42cc-b4c5-d31ffa3ba319.png">

2022-03-01 16:28 UTC, CohenIdo commented
@kfirpeled, I don't see a reason to merge this PR. it can use us for test [update package policy PR](https://github.com/build-security/kibana/pull/133). 
This task [solve](https://github.com/elastic/security-team/issues/3058) is in the right way.

2022-03-03 18:05 UTC, kfirpeled requested changes
see comments ^^

2022-03-09 10:17 UTC, kfirpeled approved these changes

2022-03-09 10:24 UTC, merged